-- SCOTT 계정 활성화
ALTER USER scott ACCOUNT UNLOCK;

-- SCOTT에게 연결할 수 있는 권한 부여
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO scott
IDENTIFIED BY tiger;

-- SCOTT에게 DBA 권한 부여
-- DBA: DATABASE ADMIN
GRANT DBA TO scott;


SELECT *
  FROM EMP;

